mysite/myauth/urls.py
from django.urls import path
from .views import set_cookie_view, get_cookie_view, set_session_view, get_session_view, \
    MyLogoutView, MyLoginView, ProfileView, RegisterView, UserListView, \
    AboutMeView, ProfileDetailView, ProfileUpdateView

app_name = "myauth"

urlpatterns = [
    path("users/", UserListView.as_view(), name="user_list"),
    path("users/<int:pk>/", ProfileDetailView.as_view(), name="profile_detail"),
    path("users/<int:pk>/edit", ProfileUpdateView.as_view(), name="profile_edit"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("about-me/", AboutMeView.as_view(), name="about_me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/set/", set_cookie_view, name="cookie_set"),
    path("cookie/get/", get_cookie_view, name="cookie_get"),
    path("session/set/", set_session_view, name="session_set"),
    path("session/get/", get_session_view, name="session_get"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .sitemaps import sitemaps

urlpatterns = [
    path('req/', include("requestapp.urls")),
    path('accounts/', include("myauth.urls")),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path('api/', include("myapiapp.urls")),
    path('__debug__/', include("debug_toolbar.urls")),
    path('sitemap.xml', sitemap, sitemaps, name="django.contrib.sitemaps.views"),
]

urlpatterns += i18n_patterns(
    path('admin/doc/', include("django.contrib.admindocs.urls")),
    path('admin/', admin.site.urls),
    path('shop/', include("shopapp.urls")),
    path('blog/', include("blogapp.urls")),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include("debug_toolbar.urls"))
    )

mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ProductListView,
    ProductDetailView, 
    ProductCreateView, 
    ProductUpdateView, 
    ProductDeleteView,  
    ShopIndexView, 
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    ExportOrdersView,
    LatestProductsFeed,
    UserOrdersListView,
    ExportUserOrdersView,
)
from .api import ProductViewSet, OrderViewSet

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("products/<int:pk>/edit", ProductUpdateView.as_view(), name="product_edit"),
    path("products/<int:pk>/deactivate", ProductDeleteView.as_view(), name="product_deactivate"),
    path("products/latest/feed/", LatestProductsFeed(), name="products_feed"),
    path("orders/", OrderListView.as_view(), name="order_list"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_detail"),
    path("orders/<int:pk>/edit", OrderUpdateView.as_view(), name="order_edit"),
    path("orders/<int:pk>/delete", OrderDeleteView.as_view(), name="order_delete"),
    path("orders/export/", ExportOrdersView.as_view(), name="export_orders"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders"),
    path("users/<int:user_id>/orders/export/", ExportUserOrdersView.as_view(), name="export_user_orders"),
]

mysite/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.shortcuts import reverse

def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename
    )

class Product(models.Model):
    class Meta:
        ordering = ["name"]
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    name = models.CharField(max_length=100, null=False, blank=False, db_index=True)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    active = models.BooleanField(default=False)
    weight = models.PositiveSmallIntegerField(default=0)
    last_change_date = models.DateTimeField(auto_now=True)
    add_date = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    @property
    def description_short(self) -> str:
        if len(self.description) < 48:
            return self.description
        return self.description[:48] + '...'

    def __str__(self) -> str:
        return f"Товар {self.name!r} (pk={self.pk})"
    
    def get_absolute_url(self):
        return reverse("shopapp:product_detail", kwargs={"pk": self.pk})
    
def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.pk,
        filename=filename
    )

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(null=True, blank=True, upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order (models.Model):
    class Meta:
        ordering = ["order_date"]        
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    order_date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(null=False, blank=True)
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")

    def __str__(self) -> str:
        return f"Заказ от пользователя {self.user!r} от {self.order_date}"
    
    def get_absolute_url(self):
        return reverse("shopapp:order_detail", kwargs={"pk": self.pk})

mysite/shopapp/forms.py
from django import forms
from django.core import validators
from .models import Product, Order

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "active", "preview"

    images = MultipleFileField()
    #name = forms.CharField(label="Наименование", max_length=100)
    #description = forms.CharField(
    #    label="Описание", 
    #    widget=forms.Textarea(attrs={"rows":5, "cols": 30}), 
    #    validators=[validators.RegexValidator(regex=r"great", message="Поле должно содержать слово 'great'")],
    #)
    #price = forms.DecimalField(label="Цена", min_value=0)
    #active = forms.BooleanField(default=False)
    #weight = forms.PositiveSmallIntegerField(default=0)
    #last_change_date = forms.DateTimeField(auto_now=True)
    #add_date = forms.DateTimeField(auto_now_add=True)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "user", "products", "delivery_address", "comment"

class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/views.py
"""
Модуль представлений.

В данном модуле описаны представления интернет-магазина
"""
import logging
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from timeit import default_timer

from django.core import serializers
from django.core.cache import cache
from .forms import ProductForm
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.contrib.syndication.views import Feed
from django.utils.translation import gettext_lazy as _
from .models import Product, Order, ProductImage

log = logging.getLogger(__name__)

class ShopIndexView(View):

    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('laptop', 'last model of laptop', 1999),
            ('desktop', 'super power pc', 2999),
            ('smartphone', 'overprice smartphone', 999),  
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
        }
        log.debug("Products for shop index: %s", products)
        log.info("Render shop index")
        return render(request, "shopapp/shop-index.html", context=context)
    
class ProductListView(ListView):
    queryset = Product.objects.filter(active=True)
    paginate_by = 10

class ProductDetailView(DetailView):
    model = Product

class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = "shopapp.add_product"
    model = Product
    fields = "name", "description", "price", "weight"
    success_url = reverse_lazy("shopapp:product_list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form) 

class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    #fields = "name", "description", "price", "weight", "preview"
    form_class = ProductForm
    template_name_suffix = '_update_form'

    def test_func(self) -> bool | None:
        user = self.request.user
        product = self.get_object()
        return user.is_superuser or (user.has_perm("shopapp.change_product") and product.created_by == user)
    
    def form_valid(self, form) -> HttpResponse:
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image,
            )

        return response

    def get_success_url(self) -> str:
        return reverse("shopapp:product_detail", kwargs={"pk": self.object.pk})

class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "shopapp.delete_product"
    queryset = Product.objects.prefetch_related("images")
    success_url = reverse_lazy("shopapp:product_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.active = False
        self.object.save()
        return HttpResponseRedirect(success_url)

class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    paginate_by = 10

class OrderDetailView(LoginRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    model = Order

class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    fields = "user", "products", "comment", "delivery_address", "promocode"
    success_url = reverse_lazy("shopapp:order_list")

class OrderUpdateView(LoginRequiredMixin, UpdateView):
    model = Order
    fields = "user", "products", "comment", "delivery_address", "promocode"
    template_name_suffix = '_update_form'

    def get_success_url(self) -> str:
        return reverse("shopapp:order_detail", kwargs={"pk": self.object.pk})
    
class OrderDeleteView(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:order_list")

class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = 'shopapp/user_orders_list.html'

    def get_queryset(self):
        self.owner = get_object_or_404(User, pk=self.kwargs["user_id"])
        return Order.objects.filter(user=self.owner)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['owner'] = self.owner
        return context
    
class ExportOrdersView(UserPassesTestMixin, View):
    
    
    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.order_by("pk").all()
        orders_data = [
            {
                "pk": order.pk,
                "delivery_address": order.delivery_address,
                "promocode": order.promocode,
                "user": order.user.pk,
                "products": [product.pk for product in order.products.order_by("pk").all()]
            }
            for order in orders 
        ]
        return JsonResponse({"orders": orders_data})
    
    def test_func(self) -> bool | None:
        user = self.request.user
        return user.is_staff
    
class ExportUserOrdersView(UserPassesTestMixin, View):
    
    def get(self, request: HttpRequest, *args, **kwargs) -> JsonResponse:
        user_id = kwargs["user_id"]
        cache_key = "orders_serialized_" + str(user_id)
        orders_serialized = cache.get(cache_key)
        if orders_serialized is None:
            owner = get_object_or_404(User, pk=user_id)
            orders = Order.objects.filter(user=owner).order_by("pk")
            orders_serialized = serializers.serialize('json', orders)
            cache.set(cache_key, orders_serialized, 300)
        return JsonResponse(orders_serialized, safe=False)

    def test_func(self) -> bool | None:
        user = self.request.user
        return user.is_staff

class LatestProductsFeed(Feed):
    title = "Products Feed"
    description = "Adding and changing products"
    link = reverse_lazy("shopapp:product_list")

    def items(self):
        return (Product.objects.filter(active=True).order_by("-last_change_date")[:10])
    
    def item_title(self, item: Product) -> str:
        return item.name
    
    def item_description(self, item: Product) -> str:
        return item.description_short

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Base Title
        {% endblock%}
    </title>
    <style>
        .red {
            color: white;
            background-color: red;
        }
    </style>
</head>
<body>
    {% block body %}
        Base Body
    {% endblock%}
    <div>
        {% now 'H:i' %}
    </div>
    <div>
        {% now 'l' as current_weekday %}
        Today is {{ current_weekday }}
    </div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Создание заказа
{% endblock %}

{% block body %}
    <h1>Создание нового заказа:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Создать</button>
        </form>
    </div>

    <div>
        <a href="{% url "shopapp:orders_list" %}">Список заказов</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Создание товара
{% endblock %}

{% block body %}
    <h1>Создание нового товара:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Создать</button>
        </form>
    </div>

    <div>
        <a href="{% url "shopapp:products_list" %}">Список товаров</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Удаление заказа {{ object.pk }} 
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить заказ #{{ object.pk }} от {{ object.order_date|date:"d.m.Y" }}?</p>
        {{ form }} 
        <button type="submit">Удалить заказ</button>
    </form>
    <hr />

    <div>
        <a href="{% url "shopapp:order_detail" pk=object.pk %}">Вернуться в свойствам заказа</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Свойства заказа {{object.pk}}
{% endblock %}

{% block body %}
    <h1>Заказ #{{ object.pk }} от {{object.order_date|date:"d.m.Y"}}</h1>

    <div>
        <p>Промокод: <code>{{ object.promocode }}</code></p>
        <p>Адрес доставки: {{ object.delivery_address }}</p>
        <p>Комментарий: {% firstof object.comment 'Без комментария' %}</p>
        <p>Покупатель: <strong>{% firstof object.user.first_name object.user.username %}</strong></p>
        <div>Список товаров:
            <ul>
                {% for product in object.products.all %}
                <li>{{ product.name }}, {{ product.price}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <hr />

    <div>
        <a href="{% url "shopapp:order_list" %}">Вернуться в список заказов</a>
        <a href="{% url "shopapp:order_edit" pk=object.pk %}">Редактирвоание заказа</a>
        <a href="{% url "shopapp:order_delete" pk=object.pk  %}">Удалить заказ</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Новый заказ
{% endblock %}

{% block body %}
    <h1>Создание нового заказа</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>
    <hr />

    <div>
        <a href="{% url "shopapp:order_list" %}">Вернуться в список заказов</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Список заказов:
{% endblock %}

{% block body %}
    <h1>Заказы:</h1>
    {% if object_list %}
        <div>
        {% for order in object_list %}
            <div>
                <p><a href="{% url "shopapp:order_detail" pk=order.pk %}">Заказ #{{ order.pk }} от {{order.order_date|date:"d.m.Y"}}</a></p>
                <p>Покупатель: <strong>{% firstof order.user.first_name order.user.username %} </strong></p>
                <p>Промокод: <code>{{ order.promocode }}</code></p>
                <p>Адрес доставки: {{ order.delivery_address }}</p>
                <p>Комментарий: {% firstof order.comment 'Без комментария' %}</p>
            </div>
            <hr />
        {% endfor %}
        </div>
    {% else %}
        <h3>Пока заказов нет</h3>
    {% endif %}

    <div>
        <a href="{% url "shopapp:order_create" %}">Форма создания заказа</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Редактирование заказа {{ object.pk}}
{% endblock %}

{% block body %}
    <h1>Редактирование заказа #{{ object.pk }} от {{ object.order_date|date:"d.m.Y" }}</h1>

    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
    <hr />

    <div>
        <a href="{% url "shopapp:order_detail" pk=object.pk %}">Вернуться к свойствам заказа</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Снятие товара {{ object.name }} с публикации
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите снять товар "{{ object.name }}" с публикации?</p>
        {{ form }} 
        <button type="submit">Снять с публикации</button>
    </form>
    <hr />

    <div>
        <a href="{% url "shopapp:product_detail" pk=object.pk %}">Вернуться в свойствам товара</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_detail.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate "Product detail" %} {{object.name}} 
{% endblock %}

{% block body %}
    <h1>{% translate "Product" %} {{object.name}}</h1>

    <div>
        <p>{% translate "Price" %}: {{ object.price }}</p>
        {% translate "no description" as no_description %}
        <p>{% translate "Description" %}: {% firstof object.description no_description %}</p>
        <p>{% translate "Weight" %}: {{ object.weight }}</p>
        <p>{% translate "Active" context 'Is Product active' %}: <input type="checkbox" disabled {% if object.active is True %} checked {% endif %}></p>
        {% if object.preview  %}
        <p>{% translate "Product preview" %}: <img src={{ object.preview.url }} alt="{{ object.name }}"></p>
        {% endif %}
        <h3>{% translate "Product images" %}:</h3>
        {% for img in object.images.all %}
            <div>
                <img src="{{ img.image.url }}" >
                <div>{{ img.image.description }}</div>
                <div>
                {% blocktranslate count image_count=object.images|length %}
                    The Product has one image
                {% plural %}                    
                    The Product has {{ image_count }} images
                {% endblocktranslate %}
                </div>
            </div>
        {% empty %}
            {% blocktranslate %}
            <div>No images yet</div>
            {% endblocktranslate %}
        {% endfor %}
    </div>
    <hr />

    <div>
        <a href="{% url "shopapp:product_list" %}">{% translate "Return to Product list" %}</a>
        {% if perms.shopapp.change_product %}
        <a href="{% url "shopapp:product_edit" pk=object.pk %}">{% translate "Edit Product" %}</a>
        {% endif %}
        {% if perms.shopapp.delete_product %}
        <a href="{% url "shopapp:product_deactivate" pk=object.pk  %}">{% translate "Deactivate Product" %}</a>
        {% endif %}
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Новый товар
{% endblock %}

{% block body %}
    <h1>Создание нового товара</h1>

    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Создать</button>
    </form>
    <hr />

    <div>
        <a href="{% url "shopapp:product_list" %}">Вернуться в список товаров</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Список товаров
{% endblock %}

{% block body %}
    <h1>Товары:</h1>
    {% if object_list  %}
        <div>
        {% for product in object_list  %}
            <div>
                <h3><a href="{% url 'shopapp:product_detail' pk=product.pk %}">{{ product.name }}</a></h3>
                <p>Цена: {{ product.price }}</p>
                <p>Описание: {% firstof product.description 'Нет описания' %}</p>
                <p>Цена: {{ product.price }}</p>
                {% if product.preview  %}
                <img src={{ product.preview.url }} alt="{{ product.name }}">
                {% endif %}
            </div>
            <hr />
        {% endfor %}
        </div>
    {% else %}
        <h3>Пока товаров нет</h3>
    {% endif %}
    
    {% if perms.shopapp.add_product %}
    <div>
        <a href="{% url "shopapp:product_create" %}">Форма создания товара</a>
    </div>
    {% endif %}

{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
Shop Index
{% endblock%}

{% block body %}
    <h1>Hello Shop Index!</h1>

    <div>
        <ul>
            {% for name, description, price in products %}
            <li>{{ name|capfirst }} ({{ name|length }}) for ${{ price|floatformat:"2" }}</li>
            <div>{{ description|capfirst }}</div>
            {% if name|length_is:'7' %}
            <span class="red">Lucky product!</span>
            {% endif %}
            {% empty %}
            No products here
            {% endfor %}
        </ul>
    </div>
    <hr>
    <h2>Меню сайта: </h2>
    <ul>
        <li><a href="{% url 'shopapp:product_list' %}">Продукты</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'shopapp:order_list' %}">Заказы</a></li>
        {% endif %}
    </ul>
    <hr>
    <div>Time running: {{ time_running }}</div>

    <div>{% lorem 3 p random %}</div>
{% endblock%}

mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    Список заказов пользователя {{ owner.username }}:
{% endblock %}

{% block body %}
    <h1>Пользователь {{ owner.username }} выполнил следующие заказы:</h1>
    {% if object_list %}
        {% cache 300 orders owner.pk %}
            <div>
            {% for order in object_list %}
                <div>
                    <p><a href="{% url "shopapp:order_detail" pk=order.pk %}">Заказ #{{ order.pk }} от {{order.order_date|date:"d.m.Y"}}</a></p>
                    <p>Промокод: <code>{{ order.promocode }}</code></p>
                    <p>Адрес доставки: {{ order.delivery_address }}</p>
                    <p>Комментарий: {% firstof order.comment 'Без комментария' %}</p>
                </div>
                <hr />
            {% endfor %}
            </div>
        {% endcache %}
    {% else %}
        <h3>У пользователя {{ owner.username }} ещё нет заказов</h3>
    {% endif %}

{% endblock %}