mysite/myauth/urls.py
from django.urls import path
from .views import set_cookie_view, get_cookie_view, set_session_view, get_session_view, \
    MyLogoutView, MyLoginView, ProfileView, RegisterView, UserListView, \
    AboutMeView, ProfileDetailView, ProfileUpdateView

app_name = "myauth"

urlpatterns = [
    path("users/", UserListView.as_view(), name="user_list"),
    path("users/<int:pk>/", ProfileDetailView.as_view(), name="profile_detail"),
    path("users/<int:pk>/edit", ProfileUpdateView.as_view(), name="profile_edit"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("about-me/", AboutMeView.as_view(), name="about_me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", MyLoginView.as_view(), name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/set/", set_cookie_view, name="cookie_set"),
    path("cookie/get/", get_cookie_view, name="cookie_get"),
    path("session/set/", set_session_view, name="session_set"),
    path("session/get/", get_session_view, name="session_get"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .sitemaps import sitemaps

urlpatterns = [
    path('req/', include("requestapp.urls")),
    path('accounts/', include("myauth.urls")),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path('api/', include("myapiapp.urls")),
    path('__debug__/', include("debug_toolbar.urls")),
    path('sitemap.xml', sitemap, sitemaps, name="django.contrib.sitemaps.views"),
]

urlpatterns += i18n_patterns(
    path('admin/doc/', include("django.contrib.admindocs.urls")),
    path('admin/', admin.site.urls),
    path('shop/', include("shopapp.urls")),
    path('blog/', include("blogapp.urls")),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include("debug_toolbar.urls"))
    )

mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User

def profile_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return "users/user_{pk}/avatar/{filename}".format(
        pk=instance.user.pk,
        filename=filename
    )

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(blank=True, null=True, upload_to=profile_avatar_directory_path)

mysite/myauth/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from .models import Profile

class DateInput(forms.DateInput):
    input_type = 'date'

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "avatar", "bio", "birthday", "agreement_accepted"
        widgets = {
            'birthday': DateInput(),
        }

mysite/myauth/views.py
from typing import Any, Optional
from django.db import models
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, UpdateView, DetailView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.utils.translation import gettext as _
from .models import Profile
from .forms import ProfileForm

class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "myauth/user_list.html"

class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = "myauth/profile_detail.html"

class ProfileUpdateView(UserPassesTestMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "myauth/profile_form.html"

    def test_func(self) -> bool | None:
        user = self.request.user
        cur_user = self.get_object().user
        return user.is_staff or (user.pk == cur_user.pk)
    
    def get_success_url(self) -> str:
        return reverse("myauth:profile_detail", kwargs={"pk": self.object.pk})

    #def form_valid(self, form) -> HttpResponse:
    #    response = super().form_valid(form)
    #    profile, created = Profile.objects.get_or_create(user=self.object)
    #    if form.files.get("avatar"):
    #        profile.avatar = form.files.get("avatar")
    #    if form.cleaned_data.get("bio"):
    #        profile.bio = form.cleaned_data.get("bio")
    #    if form.cleaned_data.get("birthday"):
    #        profile.birthday = form.cleaned_data.get("birthday")
    #    if form.cleaned_data.get("agreement_accepted"):
    #        profile.agreement_accepted = form.cleaned_data.get("agreement_accepted")
    #    profile.save()
    #    return response

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "myauth/profile.html"

class AboutMeView(LoginRequiredMixin, UpdateView):
    model = Profile
    fields = "avatar", 
    template_name = "myauth/about-me.html"
    success_url = reverse_lazy("myauth:about_me")

    def get_object(self, queryset = None):
        profile, created = self.model.objects.get_or_create(user=self.request.user)
        return profile

class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:profile")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user=user)
        return response

class MyLoginView(LoginView):
    template_name = "myauth/login.html"
    redirect_authenticated_user = True

class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")

@login_required
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = 'Неизвестный пользователь'
    response = HttpResponse("Set cookie")
    response.set_cookie("UserName", username, max_age=3600)
    return response

@login_required
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("UserName", "Значение пока не задано")
    return HttpResponse(f'Cookie value: {value!r}')

@login_required
def set_session_view(request: HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = 'Неизвестный пользователь'
    request.session["UserName"] = username
    return HttpResponse("Set session")

@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("UserName", "Значение пока не задано")
    return HttpResponse(f'Session value: {value!r}')

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    Мой профиль 
{% endblock %}

{% block body %}
    <h1>Мой профиль</h1>
    {% if user.is_authenticated %}
        <div style="display:flex;">
        <div style="width: 150px;padding:5px;margin:10px;border:1px solid black;">
            {% if object.avatar %}    
                <img src="{{ object.avatar.url }}" width="150">
            {% else %}
                <div>Нет аватара</div>
            {% endif %}
        </div>
        <div>
            <p>Логин: {{ object.user.username }}</p>
            <p>Имя: {{ object.user.first_name }}</p>
            <p>Фамилия: {{ object.user.last_name }}</p>
            <p>Email: {{ object.user.email }}</p>
            <p>Дата рождения: {{ object.birthday }}</p>
            <p>Биография: {{ object.bio }}</p>
            <p>Соглашение: {{ object.agreement_accepted }}</p>
        </div>
        <form method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Обновить аватар</button>
        </form>
    {% else %}
        <h2>Пользователь не авторизован</h2>
    {% endif%}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Base Title
        {% endblock%}
    </title>
</head>
<body>
    {% block body %}
        Base Body
    {% endblock%}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Вход на сайт         
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile.html
{% extends 'myauth/base.html' %}

{% block title %}
    Профиль пользователя    
{% endblock %}

{% block body %}
    <h1>Профиль пользователя</h1>
    {% if user.is_authenticated %}
        <div style="display:flex;">
        <div style="width: 150px;padding:5px;margin:10px;border:1px solid black;">
            {% if user.profile.avatar %}    
                <img src="{{ user.profile.avatar.url }}" width="150">
            {% else %}
                <div>Нет аватара</div>
            {% endif %}
        </div>
        <div>
            <p>Логин: {{ user.username }}</p>
            <p>Имя: {{ user.first_name }}</p>
            <p>Фамилия: {{ user.last_name }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Дата рождения: {{ user.profile.birthday }}</p>
            <p>Биография: {{ user.profile.bio }}</p>
            <p>Соглашение: {{ user.profile.agreement_accepted }}</p>
        </div>
    {% else %}
        <h2>Пользователь не авторизован</h2>
    {% endif%}
{% endblock %}

mysite/myauth/templates/myauth/profile_detail.html
{% extends 'myauth/base.html' %}

{% block title %}
    Профиль пользователя
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        <h1>Профиль пользователя {{ object.user.username }}</h1>
        <div style="display:flex;">
            <div style="width: 150px;padding:5px;margin:10px;border:1px solid black;">
                {% if object.avatar %}    
                    <img src="{{ object.avatar.url }}" width="150">
                {% else %}
                    <div>Нет аватара</div>
                {% endif %}
            </div>
            <div>
                <p>Логин: {{ object.user.username }}</p>
                <p>Имя: {{ object.user.first_name }}</p>
                <p>Фамилия: {{ object.user.last_name }}</p>
                <p>Email: {{ object.user.email }}</p>
                <p>Дата рождения: {{ object.birthday }}</p>
                <p>Биография: {{ object.bio }}</p>
                <p>Соглашение: {{ object.agreement_accepted }}</p>
            </div>
        </div>
        {% if user.is_staff or user.pk == object.user.pk %}
            <div>
                <a href="{% url 'myauth:profile_edit' pk=object.pk %}">Редактировать</a>
            </div>
        {% endif %}
    {% else %}
        <h2>Пользователь не авторизован</h2>
    {% endif%}
{% endblock %}

mysite/myauth/templates/myauth/profile_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Редактирование пользователя
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        <h1>Редактирование пользователя {{ user.username }}</h1>
        <form method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Сохранить</button>
        </form>
    {% else %}
        <h2>Пользователь не авторизован</h2>
    {% endif%}
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Регистрация пользователя    
{% endblock %}

{% block body %}
    <h1>Регистрация нового пользователя</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрировать</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user_list.html
{% extends 'myauth/base.html' %}

{% block title %}
    Список пользователей
{% endblock %}

{% block body %}
    <h1>Пользователи:</h1>
    {% if object_list  %}
        <div>
            <ul>
        {% for user in object_list  %}
            <li><a href="{% url 'myauth:profile_detail' pk=user.profile.pk %}">{{ user.username }}</a></li>
        {% endfor %}
            </ul>
        </div>
    {% else %}
        <h3>Пользователей нет</h3>
    {% endif %}
    
{% endblock %}